### ISSUE TITLE
Remarks to your documentation

### ISSUE THREAD

**Issue by grimmpp** [cvanlabe/Eltako-home-automation#1]
Hello @cvanlabe,

first of all: I really love your documentation!!! Actually, it helped me to make the start into the whole EnOcean and Eltako world before I started to continue the journey of the Eltako Integration. Thanks a lot for that! And it is even cooler to see now that you are using and describing the integration I'm working on!

While reading your documentation through same small things came up:
**Description About Device Id:**
> The first thing is id: 00-00-00-01. This is an internal HA id we're giving to this Eltako device. It does not have to match anything on your Eltako side, but keep it simple and logical.

The `id` must match the internal bus id because actuators send status update telegrams. Only if HA receives them it will display the status change. This way I will ensure that HA gets updated when e.g. pushing wall-mounted switches in parallel. Furthermore, when because of any reason there would be a network disconnection then HA were out of sync.
Addresses can be read out easily in PCT14 like you showed. But there is a catch: Addresses in PCT14 are in DEC (base 10) and in the configuration you need to provide HEX (base 16). (e.g. 11 = B)

**Regarding assigning and generating the configuration:**
I've developed a [tool ](https://github.com/grimmpp/home-assistant-eltako/tree/main/eltakodevice_discovery)which automatically "generates" (prepares) the HA configuration for you by reading the memory of the devices mounted on the bus. Furthermore, it can also directly put the sender ids into devices. For that step only you must be connected via FAM14.
I started to prepare a [GUI ](https://github.com/grimmpp/home-assistant-eltako/blob/main/eltakodevice_discovery/dd_gui.py)as well for it.
(Documentation is maybe a bit out dated.)
In [eltako14bus](https://github.com/grimmpp/eltako14bus) there is also a nice function to print out a list of all devices and there memory content. This function is called [dump](https://github.com/grimmpp/eltako14bus/tree/master/eltakobus_memory_dump).

**Comment by cvanlabe** [comment]
Thanks for the feedback @grimmpp ! And happy to hear the work done is useful for others as well. Sounds almost like perfect team work :-)

#### Regarding device ids:

So the id `00-00-00-01` isn't random as I understood from the forum thread earlier? It's really tracking the internal bus addresses? In other words, if you assigned your FSR address `250`, in HA the first channel needs to be added as `00-00-00-FA` (hex representation of decimal 250)? As far as I know, PCT14 doesn't allow any addresses above 254, so does it mean the leading digits should always be `00-00-00`? Or is it ignored and you only assess the last 2 hex digits?

If you can clarify, I will update the documentation.

#### Regarding the discovery tool

I saw it but I was unable to get it to work to be honest. I'm running HA OS on the pi and I didn't have all the right libs and dependencies available. I installed Python on it (outside of the HA Core container), a new venv, your repo, but it didn't work. It kept complaining about missing paths etc. In the end, I decided to not spend further time on it as I _thought_ I understood how it worked and got it all working. I may look into this again soon to help contribute to the library now that I understand more how it works. The code will be easier to grasp now. Do you have any contribution guidelines how to best get started?


#### Regarding the UI tool

Could we not make that part of the HA integration?

**Comment by grimmpp** [comment]
Hello @cvanlabe

**Regarding device ids**
**Yes**. Address 255 is reserved for FAM14. I don't know what's about address 0. Like you say devices can have addresses between 1 and 254. For the communication and registration in HA all address ranges are allowed also higher than 00-00-00-FF. If you e.g. have decentral actuators then device ids start with FF-??-??-??. The eltako integration allows to use both bus-mounted and decentralized actuators and sensors in parallel, although the FAM14 does not send command telegrams into the wireless network. That is really a pity. What I do is to just have two gateways FGW14-USB and FAM-USB (wireless transceiver).

**Regarding the discovery tool**
It is not meant to run it on HA machine. I only use it locally on my PC and connect via USB to FAM14. Good point! I will extend that to the docs.

**Regarding the UI tool**
I can look into it. I do not know much about the apps in HA, yet. Most likely it is more effort and has no benefits. You always need to adjust the configuration manually because I cannot get all the information with EEPs from the actuators and sensors. My plan was to provide a tool which allows you to manage your sensors and actuators and based on that information it can generate a HA config.
Right now it detects all the devices mounted on the bus and all sensors registered in those devices and puts them into a HA config file. Really often I need to work with white spaces because I do not have enough information to prepare it completely. Otherwise I would directly put it into HA. The decentralized actuators and sensors are also hard to detect.

**Comment by cvanlabe** [comment]
Do you have any official English documentation about those address ranges?

**Comment by grimmpp** [comment]
No, not even in German. This part seems to be proprietary.

**Comment by cvanlabe** [comment]
Makes sense. Can you take a look at the changes I made in the PR? Good enough to close this issue? Or you still have more remarks? :-)

**Comment by cvanlabe** [comment]
No further feedback, assuming OK. Can be reopened if needed. Thanks for the bug report!
